Update test1.yml

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -182,7 +182,12 @@ jobs:
 
           RESPONSE=$(curl -s -u "$CONFLUENCE_EMAIL:$CONFLUENCE_API_TOKEN" -X POST -H "Content-Type: application/json" -d "$JSON" "$CONFLUENCE_BASE_URL/rest/api/content")
           PAGE_ID=$(echo "$RESPONSE" | jq -r '.id')
-          echo "PAGE_ID=$PAGE_ID"
+          echo "PAGE_ID=$PAGE_ID" >> $GITHUB_ENV
+          if [ -z "$PAGE_ID" ] || [ "$PAGE_ID" = "null" ]; then
+          echo "❌ Page creation failed"
+          echo "$RESPONSE"
+          exit 1
+          fi
 
       - name: Upload Attachments
         run: |
